const database = require('./database');

// Initialize database connection
async function initDatabase() {
  try {
    await database.initDB();
    console.log('Database initialized for complete import');
  } catch (err) {
    console.error('Error initializing database:', err);
    throw err;
  }
}

// All 71 contacts from your Excel data
const allContacts = [
  {
    date_entered: '2025-08-04',
    unit_name: 'Santa Fe Senior Village',
    count1: 1,
    managed_by: 'National CORE',
    address_office_hours: '414 N. Santa Fe Avenue',
    count2: 1,
    city: 'Vista',
    website_link: 'Santa Fe Senior Village | Apartments in Vista, CA',
    notes: 'Waitlist Opens Aug. 29th @7:30 am 62 years + fully furnished. "Santa Fe Senior Village is a vibrant supportive housing community in downtown Vista, California for seniors who are unhoused or at-risk of becoming unhoused."'
  },
  {
    date_entered: '2025-08-04',
    unit_name: 'Garden Vista Apartments',
    count1: 1,
    address_office_hours: '401 West California Avenue',
    count2: 1,
    city: 'Vista'
  },
  {
    date_entered: '2025-08-05',
    unit_name: 'Bella Terra Apartments',
    count1: 1,
    managed_by: 'Greystar',
    address_office_hours: '365 Pomelo Drive',
    count2: 1,
    city: 'Vista',
    contact: 'Megan Schratwieser',
    phone_no: '760-945-1200',
    email: 'bellaterra@greystar.com',
    bedrooms: '1-3 bedrooms',
    deposit: '$500 up to 1 month rent',
    move_in_specials: 'no',
    notes: '8/5 spoke with manager and is open with partnering with San Diego Rescue Mission.'
  },
  {
    date_entered: '2025-08-05',
    unit_name: 'Sunset Springs Apartments',
    count1: 1,
    managed_by: 'Golden City Management',
    address_office_hours: '320 Pomelo',
    count2: 1,
    city: 'Vista',
    contact: 'Jose Solis',
    phone_no: '760-945-3500',
    email: 'jose@goldencitiesmanagement.com',
    bedrooms: '1-2 bedrooms',
    notes: '8/5 spoke with manager Jose and is firm on have a credit score of 600.',
    credit_score: '600'
  },
  {
    date_entered: '2025-08-05',
    unit_name: 'Softwind Point',
    count1: 1,
    managed_by: 'Greystar',
    address_office_hours: '881 Soft Wind Road',
    count2: 1,
    city: 'Vista',
    contact: 'Catalina Martinez',
    phone_no: '760-945-1020',
    email: 'softwindpoint@greystar.com',
    bedrooms: 'Studio-2 bedroom',
    deposit: '$500 and up',
    utilities_included: 'no',
    notes: '8/5 spoke with Asst Manager interested however referred me to speaking to the manager who was out.'
  },
  {
    date_entered: '2025-08-05',
    unit_name: 'Ascend 2300',
    count1: 1,
    managed_by: 'Greystar',
    address_office_hours: '2300 Rising Glen Way',
    count2: 1,
    city: 'Carlsbad',
    contact: 'Albina Neathey(lease)',
    phone_no: '877-378-4803',
    email: 'ascend2300@greystar.com',
    bedrooms: '1-3 bedrooms'
  },
  {
    date_entered: '2025-08-06',
    unit_name: 'Autumn Haze Apts',
    count1: 1,
    managed_by: 'Bob Cota Realty',
    address_office_hours: '745 Alturas Lane, Fallbrook, Ca 92028',
    count2: 1,
    city: 'Fallbrook',
    contact: 'Elisa Marshall',
    phone_no: '760-728-4654',
    email: 'cotaproperties@yahoo.com',
    bedrooms: '1-2 bedrooms',
    rent: '$1575-1910',
    deposit: 'deposit oac',
    notes: '8/6 Manager is open however states client must me the criteria to be considered and firm on having credit score 600',
    credit_score: '600'
  },
  {
    date_entered: '2025-08-06',
    unit_name: 'Towne & Country Apts',
    count1: 1,
    managed_by: 'Bob Cota Realty',
    address_office_hours: '426 Ammunition Rd',
    count2: 1,
    city: 'Fallbrook',
    contact: 'Elisa Marshall',
    phone_no: '760-728-4654',
    email: 'cotaproperties@yahoo.com',
    bedrooms: '1-2 bedrooms',
    rent: '$1675-$1890',
    deposit: 'deposit oac',
    notes: '8/6 Manager is open however states client must me the criteria to be considered and firm on having credit score 600',
    credit_score: '600'
  },
  {
    date_entered: '2025-08-06',
    unit_name: 'Fallbrook Hills Apts',
    count1: 1,
    managed_by: 'A.P.T.S. Inc',
    address_office_hours: '744 W. Fallbrook',
    count2: 1,
    city: 'Fallbrook',
    contact: 'Mayra Estrada',
    phone_no: '760-723-2617',
    email: 'mestrada@apts-inc.com',
    bedrooms: '1-2 bedrooms',
    rent: '$1800-2200',
    deposit: '$550-$650'
  },
  {
    date_entered: '2025-08-11',
    unit_name: 'Herrington Heights',
    count1: 1,
    managed_by: 'Royal Property Management Group,',
    address_office_hours: '1320 Broadway',
    count2: 1,
    city: 'San Diego',
    contact: 'Angelica Santiago',
    phone_no: '858-723-4638',
    email: 'harringtonheights@royalpropertymgmt.com',
    bedrooms: 'Studio-2 bedroom'
  },
  {
    date_entered: '2025-08-11',
    unit_name: 'Jasmine Inn',
    count1: 1,
    address_office_hours: '1335 J Street',
    count2: 1,
    city: 'San Diego',
    contact: 'Deidre',
    phone_no: '619-234-7777',
    website_link: 'jasmininn.com',
    rent: '$1,290',
    deposit: 'deposit $200'
  },
  {
    date_entered: '2025-08-11',
    unit_name: 'Lillian Place Apartments',
    count1: 1,
    address_office_hours: '1437 J Street',
    count2: 1,
    city: 'San Diego',
    phone_no: '619-231-7585',
    bedrooms: '1 bedroom',
    rent: '2035',
    deposit: 'oac'
  },
  {
    date_entered: '2025-08-11',
    unit_name: 'Vista Terrace Apartments',
    count1: 1,
    managed_by: 'Kingdom Development',
    address_office_hours: '987 Postal Way',
    count2: 1,
    city: 'Vista',
    contact: 'Teena',
    phone_no: '714-946-1326',
    email: 'Teena@kingdomdevelopment.net'
  },
  {
    date_entered: '2025-08-11',
    unit_name: 'Churchill SRO',
    count1: 1,
    managed_by: 'Hyder Co',
    address_office_hours: '827 C Street',
    count2: 1,
    city: 'San Diego',
    contact: 'Shawna',
    phone_no: '619-764-5729',
    email: 'hotelchurchill@hyderco.com',
    bedrooms: 'studios'
  },
  {
    date_entered: '2025-08-13',
    unit_name: 'Montego Apartments',
    count1: 1,
    address_office_hours: '850 East Washington',
    count2: 1,
    city: 'Escondido',
    phone_no: '(619) 907-4119',
    bedrooms: '1&2',
    notes: 'Manager(Miguel) not available during the day, they work full time. Did not talk to manager.'
  },
  {
    date_entered: '2025-08-13',
    unit_name: 'Savenna Apts.',
    count1: 1,
    managed_by: 'Majestic Property',
    address_office_hours: '902 East Washington Ave.',
    count2: 1,
    city: 'Escondido',
    phone_no: '760-994-4030',
    bedrooms: '1&2',
    deposit: '$1000 (or full months rent)',
    accepts_programs: 'Yes',
    pet_policy: 'No Pets',
    application_fee: '$5-13',
    notes: 'Additional Apartments in Escondido: Olive Tree and Juniper Gardens both in Escondido (Part of Majestic Property) Rent increases yearly by 10%',
    raise_rent_yearly: 'Yes'
  },
  {
    date_entered: '2025-08-13',
    unit_name: 'Vida Adult Living',
    count1: 1,
    managed_by: 'FBI Management',
    address_office_hours: '1070 East Washington Av',
    count2: 1,
    city: 'Escondido',
    phone_no: '760-383-8653',
    bedrooms: '1&2',
    rent: 'Prices available once you apply',
    utilities_included: 'No.',
    accepts_programs: 'Yes',
    background_check: 'Yes',
    rental_insurance: '$15 (property only not personal items)',
    notes: 'Price quotes expire in 48hours. All Applicants must be 55 plus. Additional property in Escondido (Valle at Escondido, Valle at Mission, Park, Valle at Park) Each tenant must qualify. Will not take advanced rent. Did not provide me wit her direct email she said to go to the main email (liveatvidaapts.com and follow prompts). I spoke to Shelly.'
  },
  {
    date_entered: '2025-08-13',
    unit_name: 'Valle at Escondido',
    count1: 1,
    managed_by: 'FBI Management',
    address_office_hours: '1204 N Escondido Blvd',
    count2: 1,
    city: 'Escondido, 92026',
    phone_no: 'tel:7606066887'
  },
  {
    date_entered: '2025-08-14',
    unit_name: 'Casa Grande Apartments',
    count1: 1,
    address_office_hours: '455 East Washington Ave',
    count2: 1,
    city: 'Escondido',
    contact: 'Mila Sotelo',
    phone_no: '760-745-7766',
    email: 'milavpequities.com',
    bedrooms: '1,2,3'
  },
  {
    date_entered: '2025-08-14',
    unit_name: 'Marlow Palomar Heights',
    count1: 1,
    managed_by: 'Greystar',
    address_office_hours: '101 Chamomile Glenn (10-6)',
    count2: 1,
    city: 'Escondido 92025',
    contact: '"Becca" Cook',
    phone_no: '442-775-5055',
    bedrooms: '1,2,3',
    bathrooms: '1-3.5',
    rent: 'Starting $2,500(1 bd) $2875 (2bd) $3420-4025',
    deposit: '$500(1bd), $700 (2bd), $1000 (3bd)(holding deposit)',
    utilities_included: 'No.',
    availability_date: '2025-08-01',
    requirements: 'Little emphasis on credit, but will look at delinquencies and debt/ratio income. Corporate lease available.',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    pet_policy: 'Yes',
    rental_insurance: 'Yes',
    application_fee: '$35',
    website_link: 'Marlowe Palomar Heights in Escondido, CA',
    notes: 'Accepts vouchers, new units, a lot of inventory. I spoke to Michael. He referred me to Rebecca Cook who will be in tomorrow.Reach out to management about securing a group of units at more affordable rate? We need 1. email (uniform email) from me, or K, or D? Clarify. 8/14/2025 Met with Becca. Units near Neighborhood Health. All appliances included (Samsung appliances). Corporate lease available and approved through Greystar, this takes time. We must complete application as soon as possible. Becca will reach out to Khaliah and provide details via email.',
    follow_up: '8/14/2025 Met with Becca.',
    status: 'Contacted',
    raise_rent_yearly: 'Yes'
  },
  {
    date_entered: '2025-08-14',
    unit_name: 'Autumnwoods Villas',
    count1: 1,
    managed_by: 'Green Harvest',
    address_office_hours: '418 N. Hickory',
    count2: 1,
    city: 'Escondido',
    phone_no: '(760) 740-0082',
    email: 'aptservice@rentesc.com',
    bedrooms: '1-2 bedrooms',
    bathrooms: '1-Jan',
    rent: '$1619-1 bd',
    deposit: '1,000',
    utilities_included: 'yes',
    cost_if_not_included: 'no',
    move_in_specials: 'check monthly',
    credit_score: '600',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    pet_policy: '1',
    rental_insurance: 'Yes',
    application_fee: '$40',
    website_link: 'AUTUMNWOOD VILLAS'
  },
  {
    date_entered: '2025-08-14',
    unit_name: 'Hickory Villas',
    count1: 1,
    managed_by: 'Green Harvest',
    address_office_hours: '406 N. Hickory',
    count2: 1,
    city: 'Escondido',
    phone_no: '(760) 740-0082',
    email: 'aptservice@rentesc.com',
    bedrooms: 'Studio-2 bedroom',
    bathrooms: '1&2',
    rent: '$1309 - $1639',
    deposit: '1,000',
    utilities_included: 'yes',
    cost_if_not_included: 'no',
    move_in_specials: 'check monthly',
    credit_score: '600',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    pet_policy: '1',
    rental_insurance: 'Yes',
    application_fee: '$',
    website_link: 'HICKORYWOOD VILLAS',
    notes: 'willing to consider RRH from San Diego Rescue Mission'
  },
  {
    date_entered: '2025-08-14',
    unit_name: 'Cobble Stone',
    count1: 1,
    managed_by: 'National Core',
    address_office_hours: '360 E Washington',
    count2: 1,
    city: 'Escondido',
    phone_no: '760-741-9075',
    email: 'cobblestonevillage@nationalcore.org',
    bedrooms: '3 bedrooms only',
    bathrooms: '1&2'
  },
  {
    date_entered: '2025-08-14',
    unit_name: '8181 Alision',
    count1: 1,
    address_office_hours: '8181 Alision Avenue',
    count2: 1,
    city: 'La Mesa',
    phone_no: '(619) 984-4593',
    bedrooms: '1-2 bedrooms',
    bathrooms: '1',
    rent: '2,071-2,484',
    deposit: 'oac',
    move_in_specials: 'Yes, for new residents'
  },
  {
    date_entered: '2025-08-14',
    unit_name: 'J street (SRO)',
    count1: 1,
    managed_by: 'Top Tier/ Rise Up Residential',
    address_office_hours: '3095 J Street',
    count2: 1,
    city: 'San Diego',
    contact: 'Amanda N',
    phone_no: '215-868-5957',
    website_link: 'www.riseupresidential.org',
    bedrooms: 'shared housing',
    bathrooms: '2',
    rent: '$750-1,200',
    deposit: '1,000',
    utilities_included: 'Yes',
    cost_if_not_included: 'n/a',
    move_in_specials: 'check monthly',
    requirements: '1 year lease',
    credit_score: 'n/a',
    background_check: 'yes',
    accepts_programs: 'open',
    pet_policy: 'No',
    rental_insurance: 'Yes',
    application_fee: '$50',
    website_link: 'toptierpropmanagement.com',
    notes: 'This property could be owned and managed by Top Tier Property Management. There contact information 619-507-2200'
  },
  {
    date_entered: '2025-08-15',
    unit_name: 'Paseo del Oro',
    count1: 1,
    managed_by: 'National Core',
    address_office_hours: '432 W. Mission',
    count2: 1,
    city: 'San Marcos',
    contact: 'Shanna Ramirez',
    phone_no: '760-471-4867',
    website_link: 'www.nationalCORE.org',
    notes: 'A few market rate units available. She asked that we reach out via email to provide pricing. They have units available for persons iwth AIDS thought a program called HOPWA (all based on income.)'
  },
  {
    date_entered: '2025-08-15',
    unit_name: 'Ventaliso Apt.',
    count1: 1,
    address_office_hours: '609 Richmar',
    count2: 1,
    city: 'San Marcos',
    utilities_included: 'No.',
    website_link: 'Ventaliso – Affirmed Housing',
    notes: 'Manager not available. 48 one, two and three bedroom apartments for families earning 30-60% of the area median income (A.M.I).'
  },
  {
    date_entered: '2025-08-15',
    unit_name: 'Vista Flores Apt.',
    count1: 1,
    managed_by: 'Woodspear Properties',
    address_office_hours: '240 La Flores',
    count2: 1,
    city: 'San Marcos',
    contact: 'Estela Fitzgerald',
    phone_no: '760-727-0932',
    bathrooms: '2',
    rent: '$2380-2410',
    utilities_included: 'No',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    pet_policy: 'Yes',
    website_link: 'Apartments for Rent in San Marcos CA - Vista Flores Apartments',
    notes: 'Rent increases $50 every 6 months. Pet fee $500 first pet, $300 second pet and $20 monthly. The only current vacancies are already rented out.'
  },
  {
    date_entered: '2025-08-15',
    unit_name: 'Meadow Creek',
    count1: 1,
    managed_by: 'Woodspear Properties',
    address_office_hours: '3474 Descanso Ave',
    count2: 1,
    city: 'San Marcos',
    contact: 'Esmeralda Gomez',
    phone_no: '760-727-8144',
    email: 'mgrmeadowcreek@woodspearproperties.com',
    bedrooms: '1-2 bedrooms',
    rent: '$2070-$2120 (1bd) $ 2520-2630 (2bd)',
    utilities_included: 'No',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    pet_policy: 'Yes',
    rental_insurance: 'Yes',
    application_fee: '$35',
    notes: '$250 deposit cats $20 monthly pet rent Max 2 pets.'
  },
  {
    date_entered: '2025-08-15',
    unit_name: 'Alora Apartments',
    count1: 1,
    managed_by: 'Solari Enterprise',
    address_office_hours: '604 Richmar Avenue',
    count2: 1,
    city: 'San Marcos',
    contact: 'Karine Gomez',
    phone_no: '661-273-1050',
    email: 'alora@solari-ent.com',
    bedrooms: '1-3 bedrooms',
    bathrooms: '1& 2',
    rent: '$2200-3200',
    deposit: 'oac',
    utilities_included: 'No',
    cost_if_not_included: 'No',
    move_in_specials: 'check monthly',
    requirements: '1 year lease',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    pet_policy: 'Yes',
    rental_insurance: 'Yes',
    application_fee: '$35',
    website_link: 'Alora – Affirmed Housing',
    notes: 'Open to working with us for RRH for Vista.'
  },
  {
    date_entered: '2025-08-15',
    unit_name: 'Estrella Apartments',
    count1: 1,
    managed_by: 'Solari Enterprise',
    address_office_hours: '600 Richmar Avenue',
    count2: 1,
    city: 'San Marcos',
    contact: 'Brian',
    phone_no: '661-273-1050',
    email: 'estrellaapts@solai-ent.com',
    bedrooms: '1-3 bedrooms',
    bathrooms: '1&2',
    rent: '$2200-3200',
    deposit: 'oac',
    utilities_included: 'No',
    cost_if_not_included: 'No',
    move_in_specials: 'check monthly',
    requirements: '1 year lease',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    pet_policy: 'Yes',
    rental_insurance: 'Yes',
    application_fee: '$35',
    website_link: 'Estrella – Affirmed Housing',
    notes: 'Open to working with us for RRH for Vista.'
  },
  {
    date_entered: '2025-08-15',
    unit_name: 'El Dorado II',
    count1: 1,
    address_office_hours: '309 Richmar Avenue',
    count2: 1,
    city: 'San Marcos',
    contact: 'Jessica Rojas',
    phone_no: '760-372-0191',
    email: 'jrojas@c-cdev.com',
    bedrooms: '1-3 bedrooms',
    bathrooms: '1&2',
    deposit: 'oac',
    utilities_included: 'No.',
    cost_if_not_included: 'No',
    move_in_specials: 'waitlist closed',
    requirements: '1 year lease',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    rental_insurance: 'Yes',
    application_fee: '$31',
    website_link: 'El Dorado II',
    notes: 'Two times the rent. NO Co-signers. $100 holding deposit.'
  },
  {
    date_entered: '2025-08-15',
    unit_name: 'Villa Serena',
    count1: 1,
    managed_by: 'National Core',
    address_office_hours: '339-340 Marcos Street',
    count2: 1,
    city: 'San Marcos',
    phone_no: '760-744-2450',
    email: 'villaserena@nationalcore.org',
    bedrooms: '1-3 bedrooms',
    bathrooms: '1&2'
  },
  {
    date_entered: '2025-08-15',
    unit_name: 'Margarita Apartments',
    count1: 1,
    managed_by: '760-917-',
    address_office_hours: '1424 Bonair Rd.',
    count2: 1,
    city: 'Vista',
    contact: 'Delfina',
    bedrooms: '2-3 bedrooms',
    rent: '$2,370',
    deposit: 'Depends on specials.',
    availability_date: '2025-08-18',
    notes: 'Met with Delfina. 3 rooms available currently, 2-2bd, and 1 3bd. Owners are very flexible, willing to work with tenants. Manager email- she only speaks spanish principeyangel@hotmail.com Deposits vary, when many units are available, they may include specials. She will speak to owner, but, he is currently out of of the country.',
    follow_up: '23-Aug'
  },
  {
    date_entered: '2025-08-21',
    unit_name: 'Cedar Nettleton Apartments',
    count1: 1,
    managed_by: 'Community Housing Works',
    address_office_hours: '160 Nettleton',
    count2: 1,
    city: 'Vista',
    contact: 'Yesenia Shipman',
    phone_no: '760-945-3507',
    email: 'CedarNettleton@chworks.ent',
    bedrooms: '2-4 bedrooms',
    notes: 'waitlist closed. Visit website for sister properties.'
  },
  {
    date_entered: '2025-08-21',
    unit_name: 'The Grove (Senior)',
    count1: 1,
    managed_by: 'Wakeland Housing',
    address_office_hours: '815 Civic Center Drive',
    count2: 1,
    city: 'Vista',
    phone_no: '(760) 295-0057',
    bedrooms: '1-2 bedrooms',
    requirements: 'Designed for seniors age 62 and older',
    accepts_programs: 'Yes',
    website_link: 'The Grove (Vista, CA) - Wakeland Housing and Development Corporation'
  },
  {
    date_entered: '2025-08-21',
    unit_name: 'Paseo Pointe',
    count1: 1,
    count2: 1
  },
  {
    date_entered: '2025-08-21',
    unit_name: 'Vista Blue',
    count1: 1,
    address_office_hours: '3240 Mission Center Avenue',
    count2: 1,
    city: 'Oceanside',
    bedrooms: 'studios',
    rent: '$1,725'
  },
  {
    date_entered: '2025-08-21',
    unit_name: 'Plymouth Heights Apartments',
    count1: 1,
    address_office_hours: '380 Plymouth Dr',
    count2: 1,
    city: 'Vista',
    rent: '$2000-$2200',
    notes: 'No one available on property.'
  },
  {
    date_entered: '2025-08-21',
    unit_name: 'Vista Terrace',
    count1: 1,
    managed_by: 'Panamerican Properties',
    address_office_hours: '249 Santa Fe Place',
    count2: 1,
    city: 'Vista',
    bedrooms: '2-bedrooms',
    rent: '$2,500',
    utilities_included: 'No',
    notes: 'Received apartment information from tenant, no manager on site.'
  },
  {
    date_entered: '2025-08-22',
    unit_name: 'Citrus Court',
    count1: 1,
    managed_by: 'Hoban Management , Inc',
    address_office_hours: '485 N. Citrus Ave.',
    count2: 1,
    city: 'Escondido',
    contact: 'Fernanda',
    phone_no: '760-489-1349',
    email: 'cindeet@hobanmanagement.com',
    bedrooms: '3-bedrooms (only)',
    bathrooms: '2',
    rent: '$2,995',
    utilities_included: 'No.',
    availability_date: '2025-08-22',
    requirements: '$1000 deposit , 3x earnings',
    credit_score: '640',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    website_link: 'https://www.citruscourt.com/',
    notes: 'If client does not qualify, the agency will forward the application to upper management and there is a chance they will be accepted . In some cases they can wait up to 2 weeks to get payment prior to move in. We spoke to Fernanda, she is filling in for Cindee temporarily. Additional apartments in Escondido, under the same management: Paseo Del Prado/Winsong Villa/Casa Serena'
  },
  {
    date_entered: '2025-08-22',
    unit_name: 'Birchmont Apartments 55 plus',
    count1: 1,
    address_office_hours: '1250 E Washington Ave',
    count2: 1,
    city: 'Escondido',
    contact: 'Anthony Amato',
    bedrooms: '1-2 bedrooms',
    email: 'hesmgr@amcllc.net',
    bathrooms: '2-bd',
    rent: '$1649-1bd $1949',
    utilities_included: 'No.',
    requirements: 'Need to make 1.5 amount of rent (there is a limit to how much resident can earn)',
    notes: 'Client without employment will need a "gift affidavit", rental assistance may not count as income. We spoke to Anthony Amato,he was very interested in collaborating. Anthony is also recommending our client open a bank account, before move-in if possible.'
  },
  {
    date_entered: '2025-08-22',
    unit_name: 'Springs of Escondido',
    count1: 1,
    address_office_hours: '1261 East Washington',
    count2: 1,
    city: 'Escondido',
    contact: 'Jericha Faasua',
    phone_no: '760-504-5692',
    email: 'jericha.faasua@Atriaseniorliving.com',
    notes: 'Privately owned- does not accept rental assistance or gov. assistance. Jericha was very open to meeting with us. She provided additional names for potential partners.'
  },
  {
    date_entered: '2025-08-22',
    unit_name: 'Escondido Senior Living',
    count1: 1,
    address_office_hours: '1351 E Washington Aven.',
    count2: 1,
    city: 'Escondido',
    contact: 'Carline Callaghan',
    phone_no: '760-741-3055',
    email: 'crd.escondido@escondidoseniorliving.com',
    website_link: 'Escondido Senior Living: Senior Care in North San Diego County',
    notes: 'We spoke with Esmeralda at the front desk. She has passed on our info. to Carline Callaghan, the sales director, who was not available. She spoke highly of her.'
  },
  {
    date_entered: '2025-08-22',
    unit_name: 'Citrus Grove',
    count1: 1,
    address_office_hours: '417 N Citrus Ave',
    count2: 1,
    city: 'Escondido',
    notes: 'Not for our clients- student housing.'
  },
  {
    date_entered: '2025-08-22',
    unit_name: 'Coral Tree Apartments',
    count1: 1,
    managed_by: 'Apartment Company',
    address_office_hours: '320 Smilax Road',
    count2: 1,
    city: 'San Marcos',
    phone_no: '760-727-1230',
    bedrooms: '2 bedrooms',
    bathrooms: '1 bath',
    rent: '2675',
    deposit: '1,100 oac',
    utilities_included: 'No.',
    move_in_specials: 'Call to inquire',
    requirements: 'Check monthly'
  },
  {
    date_entered: '2025-08-22',
    unit_name: 'Mariposa Apartments',
    count1: 1,
    address_office_hours: '221 Smilax Road',
    count2: 1,
    city: 'San Marcos',
    phone_no: '(760) 424-5001',
    rent: '2035-2,799',
    deposit: '700-800 oac',
    utilities_included: 'No.',
    move_in_specials: 'Call to inquire',
    requirements: 'check monthly'
  },
  {
    date_entered: '2025-08-25',
    unit_name: 'Mission Cove',
    managed_by: 'National Core (Low- Income Housing)',
    address_office_hours: '3447 Anchor Way',
    city: 'Oceanside',
    phone_no: '760-29-9383',
    email: 'missioncoveseniors@chworks.net',
    rent: 'Based on AMI',
    requirements: 'Make 1.5 rent/ based on AMI. Apply on line.',
    website_link: 'Mission Cove Family I | Apartments in Oceanside, CA',
    notes: '"Property is Low-Income Housing Tax Credit (LIHTC) for 62+ only. Units must be rented to income-qualified tenants. Owners must certify tenant incomes at move-in and often annually. A minimum % of units must be affordable. "'
  },
  {
    date_entered: '2025-08-25',
    unit_name: 'Need to inquire about Apr. Name',
    managed_by: 'The Management Works',
    city: 'Oceanside',
    contact: 'Veronica Rouster',
    phone_no: '949-698-8935',
    email: 'veronica@mgtworks.come',
    bedrooms: '2-3 bedrooms',
    rent: '$2100 -2150- 1 bd. $2500-2550- 2 bd. (depends if unit is upstairs or not)',
    deposit: '$850-1500',
    utilities_included: 'No.',
    notes: '$100 pet deposit and $50 month fee They also manage The Kentucky and Avocado Place in Fall Brook'
  },
  {
    date_entered: '2025-08-25',
    unit_name: 'Camino Colony',
    managed_by: 'Bob Cota Realty',
    address_office_hours: '1207 S. El Camino Real',
    city: 'Oceanside',
    contact: 'Daphne or Christine',
    phone_no: '760-439-0515',
    email: 'caminocl@pacbell.net',
    bedrooms: '1-3 bedrooms',
    bathrooms: '1-2bathrooms',
    rent: '2,050-2,950',
    deposit: '500 oac',
    utilities_included: 'No.',
    move_in_specials: 'Call to inquire',
    requirements: 'Make 2.5 times base the rent. No Evictions.',
    credit_score: '599',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    pet_policy: '2',
    rental_insurance: 'Yes',
    application_fee: '$45'
  },
  {
    date_entered: '2025-08-25',
    unit_name: 'Creekwood Villas Apartments',
    managed_by: 'Sunrise Management',
    address_office_hours: '3020 Oceanside Blvd',
    city: 'Oceanside',
    contact: 'Regina Whitesell',
    phone_no: '760-721-9332',
    email: 'creekwood@sunrisemgmt.com',
    bedrooms: 'Studio, 1-2 bedrooms',
    notes: '$250 Holding deposit. I spoke with Regina, she is open to working with us,however, she has had a bad experience with someone on assistance, one OD on site.'
  },
  {
    date_entered: '2025-08-25',
    unit_name: 'Canyon Creek Apartments',
    address_office_hours: '322 Garrison Street',
    city: 'Oceanside',
    contact: 'Donna',
    phone_no: '760-433-8054',
    email: 'thecanyoncreek@sbcglobal.net',
    bedrooms: '1-3 bedrooms',
    bathrooms: '1-2bathrooms',
    rent: '1995-2,450',
    deposit: '1 month rent',
    utilities_included: 'No.',
    move_in_specials: 'Call to inquire.',
    requirements: 'Make 1.5 times base rent. No Evictions',
    credit_score: '600',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    pet_policy: '2',
    rental_insurance: 'Yes/ $11',
    application_fee: '$35'
  },
  {
    date_entered: '2025-08-26',
    unit_name: 'SOFI Ocean Hills',
    address_office_hours: '3500 Windrift Way',
    city: 'Oceanside',
    contact: 'Elizabeth Lopez',
    phone_no: '760-945-2222',
    email: 'sofioceanhills@cushwake.com',
    bedrooms: '1-3 bedrooms',
    bathrooms: '1-2 bathrooms',
    rent: '$2523-2606 (1bd) $2896-2900 (2bd)',
    deposit: '$500',
    move_in_specials: 'Possible specials coming.',
    requirements: 'Make 2.5 times.',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    application_fee: '$54.64',
    notes: '"Rent is on the higher side,however – a 2 BR / 1 BA was $2,500 about 6 months ago. Current availability: 12 units (2 BR / 1 BA) and 10 units (2 BR / 2 BA). Possible opportunity to explore a master lease. I spoke with Elizabeth Lopez, who asked that we reach back out so she can update us on any price drops. $for extra such as parking ($40) p/ month. "'
  },
  {
    date_entered: '2025-08-26',
    unit_name: 'Avalon Apartments',
    address_office_hours: '701 Breeze Hill Rd.',
    city: 'Vista',
    contact: 'Joseph',
    bedrooms: '1-3 bedrooms',
    bathrooms: '2-Jan',
    rent: '$2883-1bd $2985-2bd $3936 3bd townhouse $3380',
    notes: 'I spoke with Joseph at the front desk, he provided manger information.'
  },
  {
    date_entered: '2025-08-26',
    unit_name: 'Charlamont Apartments',
    address_office_hours: '1050 La Tortuga Dr',
    city: 'Vista',
    contact: 'N/A',
    notes: 'No manager on site. Condos'
  },
  {
    date_entered: '2025-08-28',
    unit_name: 'Sage Pointe',
    managed_by: 'Solari Enterprise',
    address_office_hours: '225 Autumn Drive',
    city: 'San Marcos',
    contact: 'Karine Gomez',
    phone_no: '760-591-7937',
    bedrooms: '2-3 bedrooms',
    bathrooms: '1-2 bathrooms'
  },
  {
    date_entered: '2025-08-28',
    unit_name: 'Las Palmas Apartments',
    managed_by: 'Borba Property',
    address_office_hours: '300 W. Los Angeles Dr.',
    city: 'Vista',
    contact: 'Naomi Benitez',
    phone_no: '760-724-4132',
    email: 'laspalma@vistainternational.org',
    bedrooms: '2-3bedrooms',
    bathrooms: '1.5 bathrooms',
    rent: '$2,225.00-2,750',
    deposit: 'oac',
    application_fee: '$40',
    background_check: 'Yes',
    pet_policy: '2 max, $45 pet rent',
    rental_insurance: 'Yes',
    application_fee: '$40',
    website_link: 'Las Palmas Apartment Homes 300 W Los Angeles Dr in Vista, CA 92083 | AffordableHousing.com'
  },
  {
    date_entered: '2025-08-28',
    unit_name: 'The Knolls',
    address_office_hours: '688 Vineyard Road',
    city: 'San Marcos',
    contact: 'Olga Corona',
    phone_no: '760-744-7133',
    email: 'ocorona@c-cdev.com',
    bedrooms: '2-4 bedrooms',
    bathrooms: '1-2.5 bathrooms',
    rent: 'n/a',
    deposit: 'n/a',
    notes: 'Manager will call with update'
  },
  {
    date_entered: '2025-08-28',
    unit_name: 'Villa Serena Phase 1',
    managed_by: 'National Core (Low- Income Housing)',
    address_office_hours: '340 Marcos Street',
    city: 'San Marcos',
    contact: 'Jasmine Murillo Service Coordinator',
    phone_no: '760-798-7501',
    email: 'jamurillo@nationalcore.org',
    bedrooms: '1-3bedrooms',
    bathrooms: '1-2bathrooms',
    move_in_specials: 'waitlist closed'
  },
  {
    date_entered: '2025-08-28',
    unit_name: 'Paseo Del Oro Apartments',
    managed_by: 'National Core (Low- Income Housing)',
    address_office_hours: '432 W Mission Road',
    city: 'San Marcos',
    contact: 'Jasmine Murillo Service Coordinator',
    phone_no: '760-471-4867',
    email: 'jamurillo@nationalcore.org',
    bedrooms: '1-3bedrooms',
    bathrooms: '1-2bathrooms',
    move_in_specials: 'waitlist closed'
  },
  {
    date_entered: '2025-08-28',
    unit_name: 'Terra Cota Apartments',
    managed_by: 'Bridge Housing',
    address_office_hours: '523 Rush Drive',
    city: 'San Marcos',
    contact: 'Ruth Lopez',
    phone_no: '760-471-6151',
    email: 'RuLopez@Bridgehousing.com',
    bedrooms: '1-3 bedrooms',
    bathrooms: '1-2bedrooms',
    rent: '3 bedrooms starting1,416'
  },
  {
    date_entered: '2025-08-28',
    unit_name: 'Westlake Village Apartment',
    address_office_hours: '413 Autumn',
    city: 'San Marcos'
  },
  {
    date_entered: '2025-08-28',
    unit_name: 'Promenade@Creekside Apartments',
    address_office_hours: '2 Creekside Drive 92078',
    city: 'San Marcos',
    phone_no: '760-736-8010',
    bedrooms: 'studio-3 bedrooms',
    bathrooms: '1-2 bathrooms'
  },
  {
    date_entered: '2025-08-28',
    unit_name: 'La Valle de Vista',
    managed_by: 'Advanced Builders Properties',
    address_office_hours: '950 Taylor Street',
    city: 'Vista',
    phone_no: '760-945-9184',
    bedrooms: '1-2 bedrooms',
    bathrooms: '1 bathroom',
    rent: '$1,700-$1,900',
    deposit: 'oac',
    utilities_included: 'No',
    move_in_specials: 'call to inquire',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    pet_policy: 'Cats only',
    rental_insurance: 'Yes',
    application_fee: '$25',
    website_link: 'La Valle De Vista Apartments – Advanced Builders Properties'
  },
  {
    date_entered: '2025-08-28',
    unit_name: 'Las Flores Village',
    address_office_hours: '1411 N Las Flores Dr. 92069',
    city: 'San Marcos'
  },
  {
    date_entered: '2025-09-02',
    unit_name: 'Vista Pacifica',
    address_office_hours: '176 Cedar Road',
    city: 'Vista',
    phone_no: '760-630-4898',
    bedrooms: '1-2 bedrooms',
    bathrooms: '1 bathroom',
    deposit: 'oac',
    utilities_included: 'No',
    move_in_specials: 'call to inquire',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    pet_policy: 'emotional support',
    rental_insurance: 'Yes',
    application_fee: '$35',
    website_link: 'https://www.allenproperties.net/vista-pacifica-vista-ca/location'
  },
  {
    date_entered: '2025-09-02',
    unit_name: 'Casa de Vista',
    managed_by: 'Zia Properties',
    address_office_hours: '315 Pomelo Dr.',
    city: 'Vista',
    contact: 'Rusty Hannum',
    phone_no: '760-726-8832',
    bedrooms: '2 bedrooms',
    bathrooms: '1 bathroom',
    rent: '$2,149',
    deposit: 'oac',
    utilities_included: 'No',
    move_in_specials: 'call to inquire',
    background_check: 'Yes',
    accepts_programs: 'Yes'
  },
  {
    date_entered: '2025-09-02',
    unit_name: 'Civic Park',
    managed_by: 'Hoban Properties',
    address_office_hours: '700 Alta Vista Dr.',
    city: 'Vista',
    contact: 'Haven',
    phone_no: '619-655-2246',
    bedrooms: '1-2 bedrooms',
    bathrooms: '1 bathroom',
    rent: '$2,050',
    deposit: '$1,000',
    utilities_included: 'No',
    move_in_specials: 'call to inquire',
    availability_date: '2025-09-02',
    requirements: '3 times the rent, will consider conditional if credit score lower than 640.',
    credit_score: '640/conditional',
    background_check: 'Yes',
    accepts_programs: 'Yes',
    pet_policy: '?',
    rental_insurance: 'Yes',
    application_fee: '$25'
  },
  {
    date_entered: '2025-09-02',
    unit_name: 'Villa Del Norte',
    address_office_hours: '1610 N Santa Fe',
    city: 'Vista',
    contact: 'Riley',
    phone_no: '760-571-2398',
    bedrooms: '1 bedroom',
    bathrooms: '1 bathroom',
    rent: '$1,700',
    deposit: 'oac',
    utilities_included: 'No',
    move_in_specials: 'call to inquire',
    availability_date: '2025-09-02'
  },
  {
    date_entered: '2025-09-02',
    unit_name: 'Towne and Country',
    managed_by: 'Bob Cota',
    address_office_hours: '426 Ammunition Rd',
    city: 'Fallbrook',
    contact: 'Elisa M',
    phone_no: '760-728-4654',
    bedrooms: '2 bedroom',
    bathrooms: '1 bathroom',
    rent: '$1,875',
    deposit: '$1,400',
    utilities_included: 'Yes',
    move_in_specials: 'call to inquire',
    availability_date: '2025-09-02',
    requirements: 'No Evictions, credit score 624 or higher, no bankruptcies.',
    background_check: 'Yes',
    accepts_programs: 'Yes'
  }
];

// Function to import all contacts
async function completeImport() {
  try {
    await initDatabase();
    
    // Check if data already exists
    const existingContacts = await database.query('SELECT COUNT(*) as count FROM housing_contacts');
    const count = database.isPostgres() ? parseInt(existingContacts[0].count) : existingContacts[0].count;
    
    if (count > 0) {
      console.log(`⚠️  Database already has ${count} contacts. Skipping import to avoid duplicates.`);
      return;
    }
    
    console.log('📥 Importing all housing contacts...');
    
    const fields = [
      'date_entered', 'unit_name', 'count1', 'managed_by', 'address_office_hours',
      'count2', 'city', 'contact', 'phone_no', 'email', 'bedrooms', 'bathrooms',
      'rent', 'deposit', 'utilities_included', 'cost_if_not_included',
      'move_in_specials', 'availability_date', 'requirements', 'credit_score',
      'background_check', 'accepts_programs', 'pet_policy', 'rental_insurance',
      'application_fee', 'website_link', 'notes', 'follow_up', 'status',
      'raise_rent_yearly'
    ];
    
    let placeholders;
    if (database.isPostgres()) {
      placeholders = fields.map((_, i) => `$${i + 1}`).join(', ');
    } else {
      placeholders = fields.map(() => '?').join(', ');
    }
    
    const insertSQL = `INSERT INTO housing_contacts (${fields.join(', ')}) VALUES (${placeholders})`;
    
    let insertedCount = 0;
    let errors = 0;
    
    for (const contact of allContacts) {
      try {
        const values = fields.map(field => contact[field] || null);
        await database.query(insertSQL, values);
        insertedCount++;
        console.log(`✓ Inserted: ${contact.unit_name}`);
      } catch (err) {
        console.error(`❌ Error inserting ${contact.unit_name}:`, err);
        errors++;
      }
    }
    
    console.log(`\n🎉 Complete import finished: ${insertedCount} contacts inserted, ${errors} errors`);
    
  } catch (error) {
    console.error('💥 Import failed:', error);
    process.exit(1);
  }
}

async function main() {
  console.log(`🚀 Starting complete import of ${allContacts.length} contacts...`);
  await completeImport();
  process.exit(0);
}

// Run if called directly
if (require.main === module) {
  main();
}